---

- name: Configure host based authentication (if entries are configured).
  template:
    src: "initial_pg_hba.conf.j2"
    dest: "{{ postgresql_config_path }}/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0600
    force: yes
  notify: restart postgresql
  when: initial_postgresql_hba_entries